server:
  port: 1010
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/student?createDatabaseIfNotExist=true
    username: root
    password: ENSA2023
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  application:
    name: STUDENT-SERVICE
  config:
    import: configserver:http://localhost:9296
